
services:

  postgres:

    image: postgres:16

    container_name: xaasgrid-postgres

    environment:

      POSTGRES_DB: eaas_db

      POSTGRES_USER: eaas_user

      POSTGRES_PASSWORD: CHANGE_ME

    volumes:

      - postgres_data:/var/lib/postgresql/data

    ports:

      - "5432:5432"



  api:

    build:

      context: .

      dockerfile: docker/api/Dockerfile

    container_name: xaasgrid-api

    depends_on:

      - postgres

    ports:

      - "4000:4000"



  dashboard:

    build:

      context: .

      dockerfile: docker/dashboard/Dockerfile

    container_name: xaasgrid-dashboard

    depends_on:

      - api

    ports:

      - "3000:3000"



volumes:

  postgres_data:

