
protected_routes:


/control-centre:


required_role:

ADMIN



/operations:


required_role:

OPERATIONS



/customer:


required_role:

CUSTOMER



/partner:


required_role:

PARTNER



/investor:


required_role:

INVESTOR


