#!/usr/bin/env python3

"""
EaaSGrid Engineering Toolkit
Release Report Generator
"""

from pathlib import Path
from datetime import datetime
import json


ROOT = Path(__file__).resolve().parents[2]

VERSION_FILE = ROOT / "version.json"

REPORT_FILE = ROOT / "release-report.md"


def load_version():

    with open(VERSION_FILE) as f:
        return json.load(f)



def generate_report():

    version = load_version()

    now = datetime.now().strftime(
        "%Y-%m-%d %H:%M:%S"
    )


    report = f"""
# EaaSGrid Release Report

## Product

{version["product"]}


## Version

{version["version"]} {version["stage"]}


## Status

{version["status"]}


## Release Date

{now}


## Validation

✅ Required project files verified


## Build

✅ Production build completed successfully


## Components

- Investor Portal
- Navigation System
- Investor Content Sections
- Metadata & SEO
- Release Automation Toolkit


## Release Management

Generated by:

EaaSGrid Engineering Toolkit

"""


    REPORT_FILE.write_text(
        report.strip()
    )


    print("=" * 50)
    print("EaaSGrid Release Report")
    print("=" * 50)

    print(
        f"\n✓ Created {REPORT_FILE}"
    )



def main():

    generate_report()



if __name__ == "__main__":
    main()
