services:
  - type: web
    name: eaasgrid-investor-portal
    runtime: node
    rootDir: apps/investor-portal
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
