#!/usr/bin/env bash

set -Eeuo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="$PROJECT_ROOT/.env"
REPORT_FILE="$PROJECT_ROOT/eaasgrid-migration-state-diagnosis-report.txt"

get_env_value() {
  local key="$1"

  grep -E "^${key}=" "$ENV_FILE" 2>/dev/null \
    | head -n 1 \
    | sed "s/^${key}=//" \
    | sed 's/^"//; s/"$//' \
    | sed "s/^'//; s/'$//"
}

PGHOST="$(get_env_value PGHOST)"
PGPORT="$(get_env_value PGPORT)"
PGDATABASE="$(get_env_value PGDATABASE)"
PGUSER="$(get_env_value PGUSER)"
PGPASSWORD="$(get_env_value PGPASSWORD)"

PGHOST="${PGHOST:-127.0.0.1}"
PGPORT="${PGPORT:-5432}"
PGDATABASE="${PGDATABASE:-eaas_db}"
PGUSER="${PGUSER:-eaas_user}"

export PGHOST PGPORT PGDATABASE PGUSER PGPASSWORD

echo "=============================================="
echo " EaaSGrid Migration State Diagnosis"
echo "=============================================="
echo "Project: $PROJECT_ROOT"
echo "Started: $(date)"
echo

echo "=== CONNECTION IDENTITY ==="

psql -v ON_ERROR_STOP=1 -x \
  -c "SELECT
        current_database() AS database,
        current_user AS user,
        inet_server_addr() AS server_address,
        inet_server_port() AS server_port;"

echo
echo "=== PUBLIC TABLES ==="

psql -v ON_ERROR_STOP=1 \
  -c "SELECT schemaname, tablename
      FROM pg_catalog.pg_tables
      WHERE schemaname = 'public'
      ORDER BY tablename;"

echo
echo "=== REGISTRY OBJECT CHECK ==="

for table in \
  eaasgrid_migration_baseline \
  eaasgrid_migration_history \
  alembic_version
do
  result="$(
    psql -tA -v ON_ERROR_STOP=1 \
      -c "SELECT COALESCE(to_regclass('public.$table')::text, 'ABSENT');"
  )"

  echo "$table: $result"
done

echo
echo "=== BASELINE RECORDS ==="

if psql -tA -v ON_ERROR_STOP=1 \
  -c "SELECT to_regclass('public.eaasgrid_migration_baseline');" \
  | grep -q '^public.eaasgrid_migration_baseline$'; then

  psql -v ON_ERROR_STOP=1 \
    -c "SELECT
          id,
          migration_file,
          migration_checksum,
          alembic_revision,
          baseline_created_at
        FROM public.eaasgrid_migration_baseline
        ORDER BY id;"

else
  echo "No baseline registry table exists."
fi

echo
echo "=== DATABASE SEARCH FOR REGISTRY TABLES ==="

psql -v ON_ERROR_STOP=1 \
  -c "SELECT
        table_catalog,
        table_schema,
        table_name
      FROM information_schema.tables
      WHERE table_name ILIKE '%migration%'
      OR table_name ILIKE '%baseline%'
      ORDER BY table_catalog, table_schema, table_name;"

echo
echo "=== DATABASES ON LOCAL POSTGRESQL SERVER ==="

psql -v ON_ERROR_STOP=1 \
  -c "SELECT datname
      FROM pg_database
      WHERE datistemplate = false
      ORDER BY datname;"

{
  echo "EaaSGrid Migration State Diagnosis"
  echo "=================================="
  echo "Timestamp: $(date)"
  echo
  echo "Configured database: $PGDATABASE"
  echo "Configured user: $PGUSER"
  echo "Configured host: $PGHOST"
  echo "Configured port: $PGPORT"
  echo
  echo "The full diagnostic output was generated by this script."
} > "$REPORT_FILE"

echo
echo "=============================================="
echo " DIAGNOSIS COMPLETE"
echo "=============================================="
echo "Report: $REPORT_FILE"
echo
echo "No database changes were made."
