name: XaaSGrid Docker Build

on:

  push:
    branches:
      - main


jobs:

 build:

  runs-on: ubuntu-latest

  steps:

  - uses: actions/checkout@v4

  - name: Docker Check
    run: |
      docker --version

  - name: Build Validation
    run: |
      echo "Docker build validation ready"

